# To run this: run docker desktop, open the containing folder of this file, run `cmd`, run `docker compose up -d`.
services:
  Redis:
    container_name: zz-redis
    image: redis:7.2.4-alpine
    restart: always
    environment:
      REDIS_PWD: '${REDIS_PASS}'
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASS
    volumes:
      - zz-cache:/data
volumes:
  zz-cache:
    driver: local