# To initialize containers:
# 1. run docker desktop, 
# 1. open a terminal at the directory containing this file, 
# 1. run `docker compose up -d`

networks:
  zz-elasticnetwork:
    driver: bridge

services:
  Redis:
    container_name: zz-redis
    image: redis:7.2.4-alpine
    restart: always
    environment:
      REDIS_PWD: '${REDIS_PASS}'
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASS
    volumes:
      - zz-cache:/data

volumes:
  zz-cache:
    driver: local