networks:
  elasticnetwork:
    driver: bridge

services:

  zz-elasticsearch:
    container_name: zz-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_STACK_VERSION}
    networks:      
      - elasticnetwork
    ports:
      - ${ES_PORT}:9200
    volumes:
      - zz-els01-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  
  zz-kibana:
    container_name: zz-kibana
    networks:      
      - elasticnetwork
    depends_on:
      - zz-elasticsearch
    image: docker.elastic.co/kibana/kibana:${ELK_STACK_VERSION}
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200 
      # - ELASTICSEARCH_HOSTS=http://localhost:9200
      # - ELASTICSEARCH_USERNAME=kibana_system
      # - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

volumes:
  zz-els01-data:
  